### ISSUE TITLE
TypeError: Forward() Takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by Oguzhanercan** [ExplainableML/ReNO#6]
Hi, I get the error at title for the line https://github.com/ExplainableML/ReNO/blob/e4161803f53c66aa5c5f8fd59bc559f1b7cec166/models/RewardStableDiffusionXL.py#L284

I did not touch anything but prompt, what would be the problem? The model I use is Hyper SDXL

**Comment by sgk98** [comment]
Hi, I just rechecked running HyperSDXL and it was running fine for me. However, I think we've mostly only tested all of this on more recent versions of diffusers (>=0.27), so that might be the issue. Otherwise, looking at the code, I don't see why there should be any problems with the call to the U-Net here.
